version: 2
updates:
  # Enable version updates for maven
  - package-ecosystem: "maven"
    # Look for `pom.xml` in the `root` directory
    directory: "/"
    # Check for updates once daily
    schedule:
      interval: "daily"

  # Enable version updates for docker
  - package-ecosystem: "docker"
    directory: "deploy"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"