version: "3.8"

services:

  ### Anwendung ###

  TimeService:
    image: ghcr.io/jexxa-projects/timeservice:latest
    ports:
      - "7502:7502"

    healthcheck:
      test: ["CMD-SHELL", "wget -nv -t1 --spider 'http://localhost:7502/BoundedContext/isRunning/'"]
      interval: 10s
      timeout: 10s
      retries: 3

    deploy:
      replicas: 2
      update_config:
        order: start-first        # Configure rolling updates
        failure_action: rollback

      rollback_config:
        parallelism: 1            # Rollback config
        order: start-first

      restart_policy:
        condition: on-failure


  ### Infrastruktur ###

  ActiveMQ:
    image: quay.io/artemiscloud/activemq-artemis-broker:latest
    restart: always
    environment:
      AMQ_USER: "admin"
      AMQ_PASSWORD: "admin"

  Postgres:
    image: postgres:14.2-alpine
    user: postgres

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "postgres"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
